### PR TITLE
ln/path: use Draw2D instead of Cairo for a pure-Go build

### PR DESCRIPTION
**Pull request by fogleman**
This partially addresses fogleman/ln#3, with the benefit of not
requiring OpenGL.  I'm sure the performance is suboptimal, but this
was so simple I couldn't resist.

### CODE REVIEW

**Comment by bpowers** [comment]
cool!  let me know if you have concerns, or if there is anything in particular I could do to test this better.

**Comment by fogleman** [comment]
Just trying to figure out why draw2d doesn't respect the join & cap style.

**Comment by fogleman** [comment]
Looks like draw2d is just using this under the covers:

https://github.com/golang/freetype

I might see about using that directly instead.

Thanks for the contribution! cairo can be a pain to install for some people.

**Comment by bpowers** [comment]
Thank you! Super cool library you have here

**Pull request merged**
